cat: .experiment_zone: No such file or directory
Request issued for: [node-4]
done: true
metadata:
  '@type': type.googleapis.com/google.cloud.common.OperationMetadata
  apiVersion: v1
  cancelRequested: false
  createTime: '2021-04-26T22:41:46.890851150Z'
  endTime: '2021-04-26T22:42:24.827279549Z'
  target: projects/red-atlas-305317/locations/europe-west4-a/nodes/node-4
  verb: update
name: projects/red-atlas-305317/locations/europe-west4-a/operations/operation-1619476906876-5c0e7d9c1a018-e667cb6b-8e153a68
response:
  '@type': type.googleapis.com/google.cloud.tpu.v1.Node
  acceleratorType: v3-8
  apiVersion: V1
  cidrBlock: 10.117.66.216/29
  createTime: '2021-03-13T04:41:22.291533178Z'
  health: HEALTHY
  ipAddress: 10.117.66.218
  name: projects/red-atlas-305317/locations/europe-west4-a/nodes/node-4
  network: global/networks/default
  networkEndpoints:
  - ipAddress: 10.117.66.218
    port: 8470
  port: '8470'
  schedulingConfig: {}
  serviceAccount: service-276208758346@cloud-tpu.iam.gserviceaccount.com
  state: READY
  tensorflowVersion: 2.4.1
Waiting for operation [projects/red-atlas-305317/locations/europe-west4-a/operations/operation-1619476906876-5c0e7d9c1a018-e667cb6b-8e153a68] to complete...
....................................................................................................................................................................................................done.
europe-west4-a
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cam2tensorflow/TensorFlowModels/yolo/train_vm.py", line 157, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/cam2tensorflow/TensorFlowModels/yolo/train_vm.py", line 115, in main
    params = train_utils.parse_configuration(FLAGS)
  File "/home/cam2tensorflow/TensorFlowModels/official/core/train_utils.py", line 249, in parse_configuration
    params, config_file, is_strict=True)
  File "/home/cam2tensorflow/TensorFlowModels/official/modeling/hyperparams/params_dict.py", line 441, in override_params_dict
    params.override(yaml.load(f, Loader=yaml.FullLoader), is_strict)
  File "/usr/local/lib/python3.7/dist-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.7/dist-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.7/dist-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.7/dist-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib/python3.7/dist-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 117, in read
    self._preread_check()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: yolo/configs/experiments/darknet/tpu/darknet53-p5.yaml; No such file or directory
darknet_classification
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   221    0     2  100   219     11   1280 --:--:-- --:--:-- --:--:--  1292
okRequest issued for: [node-4]
Waiting for operation [projects/red-atlas-305317/locations/europe-west4-a/operations/operation-1619476950278-5c0e7dc57e318-d59ce198-b18a1f42] to complete...
.............................................................................aborted by ctrl-c.
ERROR: (gcloud.compute.tpus.stop) Aborting wait for operation https://tpu.googleapis.com/v1alpha1/projects/red-atlas-305317/locations/europe-west4-a/operations/operation-1619476950278-5c0e7dc57e318-d59ce198-b18a1f42.

